Dev
baileyjrob/TutoringSystem pull request #30
Opened 2021-03-31 06:37 UTC by baileyjrob

Regular Update

2021-04-01 20:42 UTC, alatham21 approved these changes
Looks good

2021-04-01 20:44 UTC, alatham21 requested changes
looks like this is failing tests. Was this fixed in your other PR?

2021-04-01 21:43 UTC, baileyjrob commented
> looks like this is failing tests. Was this fixed in your other PR?
Not yet. My PR just added the temporary fix for the hour checking. Cameron was going to fix the bug, I believe, but I think there was an issue with his fix. I'm not sure if he's addressed it yet.

2021-04-04 20:15 UTC, FrozenLion commented
> > looks like this is failing tests. Was this fixed in your other PR?
> 
> Not yet. My PR just added the temporary fix for the hour checking. Cameron was going to fix the bug, I believe, but I think there was an issue with his fix. I'm not sure if he's addressed it yet.

Originally I thought this was a problem with my pull request because of some lines in the schema.db that I deleted. Turns out those lines didn't matter at all. Currently, I don't know what the cause of the problem is and I'm having difficulties figuring that out.

2021-04-05 21:32 UTC, alatham21 commented on app/views/tutoring_session_mailer/link_action_email.text.erb
> +  If you think this is an error, you can contact the tutor at <%= @to.email %>.
great addition!

2021-04-05 21:34 UTC, alatham21 approved these changes
Great additions. The email content was very informative.

2021-04-05 23:04 UTC, merged